# Generated by Django 3.1.3 on 2021-01-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('thumbnail', models.CharField(default='', max_length=3000)),
                ('concept', models.CharField(default='', max_length=10000)),
                ('article_title', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=3000)),
                ('article_content', models.CharField(default='', max_length=10000)),
                ('article_title1', models.CharField(blank=True, default='', max_length=100)),
                ('image1', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content1', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title2', models.CharField(blank=True, default='', max_length=100)),
                ('image2', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content2', models.CharField(blank=True, default='', max_length=10000)),
            ],
        ),
    ]
