# Generated by Django 3.1.3 on 2021-01-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='auto_increment_id',
        ),
    ]
