# Generated by Django 3.1.3 on 2021-01-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210110_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('thumbnail', models.CharField(default='', max_length=3000)),
                ('concept', models.CharField(default='', max_length=10000)),
                ('article_title', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=3000)),
                ('article_content', models.CharField(default='', max_length=10000)),
                ('article_title1', models.CharField(blank=True, default='', max_length=100)),
                ('image1', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content1', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title2', models.CharField(blank=True, default='', max_length=100)),
                ('image2', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content2', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title3', models.CharField(blank=True, default='', max_length=100)),
                ('image3', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content3', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title4', models.CharField(blank=True, default='', max_length=100)),
                ('image4', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content4', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title5', models.CharField(blank=True, default='', max_length=100)),
                ('image5', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content5', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title6', models.CharField(blank=True, default='', max_length=100)),
                ('image6', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content6', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title7', models.CharField(blank=True, default='', max_length=100)),
                ('image7', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content7', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title8', models.CharField(blank=True, default='', max_length=100)),
                ('image8', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content8', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title9', models.CharField(blank=True, default='', max_length=100)),
                ('image9', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content9', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title10', models.CharField(blank=True, default='', max_length=100)),
                ('image10', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content10', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title11', models.CharField(blank=True, default='', max_length=100)),
                ('image11', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content11', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title12', models.CharField(blank=True, default='', max_length=100)),
                ('image12', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content12', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title13', models.CharField(blank=True, default='', max_length=100)),
                ('image13', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content13', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title14', models.CharField(blank=True, default='', max_length=100)),
                ('image14', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content14', models.CharField(blank=True, default='', max_length=10000)),
                ('article_title15', models.CharField(blank=True, default='', max_length=100)),
                ('image15', models.CharField(blank=True, default='', max_length=3000)),
                ('article_content15', models.CharField(blank=True, default='', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
