# Generated by Django 3.1.3 on 2021-01-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210111_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='overview',
            field=models.CharField(default='', max_length=500),
        ),
    ]
