# Generated by Django 3.1.3 on 2021-01-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20210111_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='affiliate',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('name2', models.CharField(max_length=100)),
                ('image2', models.CharField(max_length=1000)),
                ('link2', models.CharField(max_length=1000)),
            ],
        ),
    ]
