# Generated by Django 3.1.3 on 2021-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_pizza_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='content',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='thumbnail',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
