# Generated by Django 3.1.3 on 2021-01-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210112_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_content15',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
