# Generated by Django 3.1.3 on 2021-01-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20210112_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_content',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content1',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content10',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content11',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content12',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content13',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content14',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content2',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content3',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content4',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content5',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content6',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content7',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content8',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_content9',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
