# Generated by Django 3.1.3 on 2021-01-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210110_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
