# Generated by Django 3.1.3 on 2021-12-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact_text',
        ),
    ]
