# Generated by Django 3.1.3 on 2021-12-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20211210_2100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_text',
            new_name='contacts',
        ),
    ]
